build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torch==2.3.0"
    - "accelerate==0.30.1"
    - "transformers==4.41.0"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.29.1"
